PRAGMA foreign_keys = OFF;
DELETE FROM teaching_schedules;
DELETE FROM teachers;
DELETE FROM users WHERE role = 'Guru';
DELETE FROM subjects;
DELETE FROM classes;
INSERT INTO teachers (id, name, email) VALUES ('teacher-1', 'Ustadz Muhammad Arya Mukti, Al Hafizh', 'aryamukti@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-1', 'Ustadz Muhammad Arya Mukti, Al Hafizh', 'aryamukti@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-1');
INSERT INTO teachers (id, name, email) VALUES ('teacher-2', 'Ustadz Akmal Firmana, ST.', 'akmal@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-2', 'Ustadz Akmal Firmana, ST.', 'akmal@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-2');
INSERT INTO teachers (id, name, email) VALUES ('teacher-3', 'Ustadz Abdul Kholif', 'abdulkholif@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-3', 'Ustadz Abdul Kholif', 'abdulkholif@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-3');
INSERT INTO teachers (id, name, email) VALUES ('teacher-4', 'Ustadz Sahmura Maula Maghribi, S.Mat.', 'sahmura@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-4', 'Ustadz Sahmura Maula Maghribi, S.Mat.', 'sahmura@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-4');
INSERT INTO teachers (id, name, email) VALUES ('teacher-5', 'Ustadz Muhammad Hafizh Hibatullah, S.Si.', 'hafizh@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-5', 'Ustadz Muhammad Hafizh Hibatullah, S.Si.', 'hafizh@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-5');
INSERT INTO teachers (id, name, email) VALUES ('teacher-6', 'Ustadz Faqih Hidayat, Lc.', 'faqih@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-6', 'Ustadz Faqih Hidayat, Lc.', 'faqih@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-6');
INSERT INTO teachers (id, name, email) VALUES ('teacher-7', 'Ustadz Muhammad Abdul Malik Ibrahim, S.Kom.', 'abdulmalik@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-7', 'Ustadz Muhammad Abdul Malik Ibrahim, S.Kom.', 'abdulmalik@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-7');
INSERT INTO teachers (id, name, email) VALUES ('teacher-8', 'Ustadz Dzulfikar Tri Bagaskara, S.Ag., M.Pd.', 'dzulfikar@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-8', 'Ustadz Dzulfikar Tri Bagaskara, S.Ag., M.Pd.', 'dzulfikar@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-8');
INSERT INTO teachers (id, name, email) VALUES ('teacher-9', 'Ustadzah Hasri Haryani Direja, S.Ds.', 'hasri@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-9', 'Ustadzah Hasri Haryani Direja, S.Ds.', 'hasri@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-9');
INSERT INTO teachers (id, name, email) VALUES ('teacher-10', 'Ustadzah Saiba Musyayia', 'saibamusyayia@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-10', 'Ustadzah Saiba Musyayia', 'saibamusyayia@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-10');
INSERT INTO teachers (id, name, email) VALUES ('teacher-11', 'Ustadz Rezkidar', 'rezkidar@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-11', 'Ustadz Rezkidar', 'rezkidar@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-11');
INSERT INTO teachers (id, name, email) VALUES ('teacher-12', 'Ustadz Azri Robani Indra Robbi, S.Ag.', 'azri@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-12', 'Ustadz Azri Robani Indra Robbi, S.Ag.', 'azri@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-12');
INSERT INTO teachers (id, name, email) VALUES ('teacher-13', 'Ustadzah Indri Nurbidari, S.Si', 'indri@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-13', 'Ustadzah Indri Nurbidari, S.Si', 'indri@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-13');
INSERT INTO teachers (id, name, email) VALUES ('teacher-14', 'Ustadzah Bela Dwi Lestari, S.Pd.', 'bela@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-14', 'Ustadzah Bela Dwi Lestari, S.Pd.', 'bela@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-14');
INSERT INTO teachers (id, name, email) VALUES ('teacher-15', 'Ustadzah Nurika Nuralifah, S.Ag.', 'nurika@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-15', 'Ustadzah Nurika Nuralifah, S.Ag.', 'nurika@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-15');
INSERT INTO teachers (id, name, email) VALUES ('teacher-16', 'Ustadzah Azizah Nur Aini, S.Pd.', 'azizah@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-16', 'Ustadzah Azizah Nur Aini, S.Pd.', 'azizah@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-16');
INSERT INTO teachers (id, name, email) VALUES ('teacher-17', 'Ustadz Umar Alamuddin, Lc., Al-Hafizh', 'umar@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-17', 'Ustadz Umar Alamuddin, Lc., Al-Hafizh', 'umar@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-17');
INSERT INTO teachers (id, name, email) VALUES ('teacher-18', 'Ustadz Nashiruddin Karim, Lc., Al-Hafizh', 'karim@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-18', 'Ustadz Nashiruddin Karim, Lc., Al-Hafizh', 'karim@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-18');
INSERT INTO teachers (id, name, email) VALUES ('teacher-19', 'Ustadz Yunan Hidayat, Al Hafizh', 'yunan@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-19', 'Ustadz Yunan Hidayat, Al Hafizh', 'yunan@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-19');
INSERT INTO teachers (id, name, email) VALUES ('teacher-20', 'Ustadz Muhammad Latief Amiruddin, S.T.', 'latief@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-20', 'Ustadz Muhammad Latief Amiruddin, S.T.', 'latief@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-20');
INSERT INTO teachers (id, name, email) VALUES ('teacher-21', 'Ustadzah Hasna Halimatun Basyaria, S.Ag., Al Hafizhah', 'hasna@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-21', 'Ustadzah Hasna Halimatun Basyaria, S.Ag., Al Hafizhah', 'hasna@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-21');
INSERT INTO teachers (id, name, email) VALUES ('teacher-22', 'Ustadz Tubagus Ahadiyat Rachmadi Luhur, S. Ag.', 'tubagus@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-22', 'Ustadz Tubagus Ahadiyat Rachmadi Luhur, S. Ag.', 'tubagus@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-22');
INSERT INTO teachers (id, name, email) VALUES ('teacher-23', 'Ustadz Fredy Susilo Supriyanto, S.Ag., Al Hafizh', 'fredy@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-23', 'Ustadz Fredy Susilo Supriyanto, S.Ag., Al Hafizh', 'fredy@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-23');
INSERT INTO teachers (id, name, email) VALUES ('teacher-24', 'Ustadz Aidil Aqli, S.Ag.', 'aidil@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-24', 'Ustadz Aidil Aqli, S.Ag.', 'aidil@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-24');
INSERT INTO teachers (id, name, email) VALUES ('teacher-25', 'Ustadzah Aulia Anim Amanillah', 'anim@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-25', 'Ustadzah Aulia Anim Amanillah', 'anim@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-25');
INSERT INTO teachers (id, name, email) VALUES ('teacher-26', 'Ustadzah Lina Ayu Fitriyyah, S. Ag.', 'lina@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-26', 'Ustadzah Lina Ayu Fitriyyah, S. Ag.', 'lina@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-26');
INSERT INTO teachers (id, name, email) VALUES ('teacher-27', 'Ustadz Farhan Akhandi', 'farhan@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-27', 'Ustadz Farhan Akhandi', 'farhan@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-27');
INSERT INTO teachers (id, name, email) VALUES ('teacher-28', 'Ustadz Abdullah', 'abdullah@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-28', 'Ustadz Abdullah', 'abdullah@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-28');
INSERT INTO teachers (id, name, email) VALUES ('teacher-29', 'Ustadz Aqib', 'aqib@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-29', 'Ustadz Aqib', 'aqib@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-29');
INSERT INTO teachers (id, name, email) VALUES ('teacher-30', 'Ustadzah Iffah', 'iffah@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-30', 'Ustadzah Iffah', 'iffah@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-30');
INSERT INTO teachers (id, name, email) VALUES ('teacher-31', 'Ustadzah Rifanisa', 'fani@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-31', 'Ustadzah Rifanisa', 'fani@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-31');
INSERT INTO teachers (id, name, email) VALUES ('teacher-32', 'Ustadzah Dila', 'dila@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-teacher-32', 'Ustadzah Dila', 'dila@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 'teacher-32');
INSERT INTO subjects (id, name, category) VALUES ('sub-2', 'Tahsin', 'Al-Qur''an');
INSERT INTO subjects (id, name, category) VALUES ('sub-3', 'Tajwid', 'Al-Qur''an');
INSERT INTO subjects (id, name, category) VALUES ('sub-20', 'Muraja''ah Hafalan', 'Al-Qur''an');
INSERT INTO subjects (id, name, category) VALUES ('sub-5', 'Aqidah', 'Diniyah');
INSERT INTO subjects (id, name, category) VALUES ('sub-6', 'Akhlaq', 'Diniyah');
INSERT INTO subjects (id, name, category) VALUES ('sub-7', 'Fiqih', 'Diniyah');
INSERT INTO subjects (id, name, category) VALUES ('sub-8', 'Adab wa Tarbiyah', 'Diniyah');
INSERT INTO subjects (id, name, category) VALUES ('sub-9', 'Siroh', 'Diniyah');
INSERT INTO subjects (id, name, category) VALUES ('sub-10', 'Manhaji', 'Diniyah');
INSERT INTO subjects (id, name, category) VALUES ('sub-11', 'Jazary', 'Diniyah');
INSERT INTO subjects (id, name, category) VALUES ('sub-12', 'Khot', 'Diniyah');
INSERT INTO subjects (id, name, category) VALUES ('sub-13', 'Arabiyah Baina Yadaik (ABY)', 'Bahasa');
INSERT INTO subjects (id, name, category) VALUES ('sub-14', 'Bahasa Indonesia', 'Bahasa');
INSERT INTO subjects (id, name, category) VALUES ('sub-15', 'Bahasa Inggris', 'Bahasa');
INSERT INTO subjects (id, name, category) VALUES ('sub-16', 'Matematika', 'Umum');
INSERT INTO subjects (id, name, category) VALUES ('sub-17', 'IPA', 'Umum');
INSERT INTO subjects (id, name, category) VALUES ('sub-18', 'Furusiyah', 'Umum');
INSERT INTO subjects (id, name, category) VALUES ('sub-19', 'Tai Chi / Olah Raga', 'Umum');
INSERT INTO classes (id, name, level) VALUES ('cls-1', 'I''dad Putra', 'I''dad');
INSERT INTO classes (id, name, level) VALUES ('cls-2', 'I''dad Putri', 'I''dad');
INSERT INTO classes (id, name, level) VALUES ('cls-3', 'Kelas VII Putra', 'Wustho');
INSERT INTO classes (id, name, level) VALUES ('cls-4', 'Kelas VII Putri', 'Wustho');
INSERT INTO classes (id, name, level) VALUES ('cls-5', 'Kelas VIII Putra', 'Wustho');
INSERT INTO classes (id, name, level) VALUES ('cls-6', 'Kelas VIII Putri', 'Wustho');
INSERT INTO classes (id, name, level) VALUES ('cls-7', 'Kelas IX Putra', 'Wustho');
