PRAGMA foreign_keys = OFF;
DELETE FROM teaching_schedules;
DELETE FROM teachers;
DELETE FROM subjects;
DELETE FROM users WHERE role = 'Guru';
INSERT INTO teachers (id, name, email) VALUES ('t-0', 'Ust. Abdul Malik', 'guru0@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-0', 'Ust. Abdul Malik', 'guru0@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-0');
INSERT INTO teachers (id, name, email) VALUES ('t-1', 'Ust. Umar', 'guru1@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-1', 'Ust. Umar', 'guru1@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-1');
INSERT INTO teachers (id, name, email) VALUES ('t-2', 'Ust. Dzulfikar', 'guru2@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-2', 'Ust. Dzulfikar', 'guru2@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-2');
INSERT INTO teachers (id, name, email) VALUES ('t-3', 'Ust. Karim', 'guru3@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-3', 'Ust. Karim', 'guru3@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-3');
INSERT INTO teachers (id, name, email) VALUES ('t-4', 'Ust. Fredy', 'guru4@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-4', 'Ust. Fredy', 'guru4@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-4');
INSERT INTO teachers (id, name, email) VALUES ('t-5', 'Ust. Abdullah', 'guru5@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-5', 'Ust. Abdullah', 'guru5@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-5');
INSERT INTO teachers (id, name, email) VALUES ('t-6', 'Usth.Anim', 'guru6@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-6', 'Usth.Anim', 'guru6@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-6');
INSERT INTO teachers (id, name, email) VALUES ('t-7', 'Ust. Agib', 'guru7@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-7', 'Ust. Agib', 'guru7@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-7');
INSERT INTO teachers (id, name, email) VALUES ('t-8', 'Usth.Iffah', 'guru8@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-8', 'Usth.Iffah', 'guru8@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-8');
INSERT INTO teachers (id, name, email) VALUES ('t-9', 'Ust. Yunan', 'guru9@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-9', 'Ust. Yunan', 'guru9@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-9');
INSERT INTO teachers (id, name, email) VALUES ('t-10', 'Ust. Faqih', 'guru10@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-10', 'Ust. Faqih', 'guru10@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-10');
INSERT INTO teachers (id, name, email) VALUES ('t-11', 'Usth. Indri', 'guru11@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-11', 'Usth. Indri', 'guru11@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-11');
INSERT INTO teachers (id, name, email) VALUES ('t-12', 'Ust. Aidil', 'guru12@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-12', 'Ust. Aidil', 'guru12@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-12');
INSERT INTO teachers (id, name, email) VALUES ('t-13', 'Usth. Saiba Musyaiya', 'guru13@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-13', 'Usth. Saiba Musyaiya', 'guru13@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-13');
INSERT INTO teachers (id, name, email) VALUES ('t-14', 'Ust. Arya', 'guru14@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-14', 'Ust. Arya', 'guru14@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-14');
INSERT INTO teachers (id, name, email) VALUES ('t-15', 'Ust. Kholif', 'guru15@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-15', 'Ust. Kholif', 'guru15@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-15');
INSERT INTO teachers (id, name, email) VALUES ('t-16', 'Usth. Bela', 'guru16@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-16', 'Usth. Bela', 'guru16@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-16');
INSERT INTO teachers (id, name, email) VALUES ('t-17', 'Ust. Farhan', 'guru17@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-17', 'Ust. Farhan', 'guru17@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-17');
INSERT INTO teachers (id, name, email) VALUES ('t-18', 'Ust. Tubagus', 'guru18@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-18', 'Ust. Tubagus', 'guru18@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-18');
INSERT INTO teachers (id, name, email) VALUES ('t-19', 'Ust. Hafizh', 'guru19@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-19', 'Ust. Hafizh', 'guru19@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-19');
INSERT INTO teachers (id, name, email) VALUES ('t-20', 'Usth. Fani', 'guru20@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-20', 'Usth. Fani', 'guru20@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-20');
INSERT INTO teachers (id, name, email) VALUES ('t-21', 'Ust. Azri', 'guru21@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-21', 'Ust. Azri', 'guru21@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-21');
INSERT INTO teachers (id, name, email) VALUES ('t-22', 'Usth. Dila', 'guru22@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-22', 'Usth. Dila', 'guru22@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-22');
INSERT INTO teachers (id, name, email) VALUES ('t-23', 'Usth. Azizah', 'guru23@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-23', 'Usth. Azizah', 'guru23@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-23');
INSERT INTO teachers (id, name, email) VALUES ('t-24', 'Usth. Hasri', 'guru24@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-24', 'Usth. Hasri', 'guru24@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-24');
INSERT INTO teachers (id, name, email) VALUES ('t-25', 'Ust. Latief', 'guru25@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-25', 'Ust. Latief', 'guru25@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-25');
INSERT INTO teachers (id, name, email) VALUES ('t-26', 'Ust. Akmal', 'guru26@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-26', 'Ust. Akmal', 'guru26@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-26');
INSERT INTO teachers (id, name, email) VALUES ('t-27', 'Usth. Lina', 'guru27@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-27', 'Usth. Lina', 'guru27@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-27');
INSERT INTO teachers (id, name, email) VALUES ('t-28', 'Ust. Rezkidar', 'guru28@mqba.sch.id');
INSERT INTO users (id, name, email, passwordHash, role, teacher_id) VALUES ('u-28', 'Ust. Rezkidar', 'guru28@mqba.sch.id', '$2b$10$guru123hashed', 'Guru', 't-28');
INSERT INTO subjects (id, name, category) VALUES ('s-0', 'Khot', 'Al-Qur''an');
INSERT INTO subjects (id, name, category) VALUES ('s-1', 'Aqidah', 'Diniyah');
INSERT INTO subjects (id, name, category) VALUES ('s-2', 'Bhs. Inggris', 'Bahasa');
INSERT INTO subjects (id, name, category) VALUES ('s-3', 'Fiqih', 'Diniyah');
INSERT INTO subjects (id, name, category) VALUES ('s-4', 'ABY', 'Bahasa');
INSERT INTO subjects (id, name, category) VALUES ('s-5', 'Matematika', 'Umum');
INSERT INTO subjects (id, name, category) VALUES ('s-6', 'Tajwid', 'Al-Qur''an');
INSERT INTO subjects (id, name, category) VALUES ('s-7', 'Akhlaq', 'Diniyah');
INSERT INTO subjects (id, name, category) VALUES ('s-8', 'Tahsin', 'Al-Qur''an');
INSERT INTO subjects (id, name, category) VALUES ('s-9', 'Tilawah', 'Al-Qur''an');
INSERT INTO subjects (id, name, category) VALUES ('s-10', 'Siroh', 'Diniyah');
INSERT INTO subjects (id, name, category) VALUES ('s-11', 'IPA', 'Umum');
INSERT INTO subjects (id, name, category) VALUES ('s-12', 'Bhs. Indonesia', 'Bahasa');
INSERT INTO subjects (id, name, category) VALUES ('s-13', 'Adab', 'Diniyah');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-0', 'Sabtu', '10:00 - 10:45', 'cls-1', 't-0', 's-0', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-1', 'Sabtu', '10:00 - 10:45', 'cls-2', 't-1', 's-1', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-2', 'Sabtu', '10:00 - 10:45', 'cls-3', 't-2', 's-2', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-3', 'Sabtu', '10:00 - 10:45', 'cls-4', 't-3', 's-3', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-4', 'Sabtu', '10:00 - 10:45', 'cls-5', 't-4', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-5', 'Sabtu', '10:00 - 10:45', 'cls-6', 't-5', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-6', 'Sabtu', '10:00 - 10:45', 'cls-7', 't-6', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-7', 'Sabtu', '10:45 - 11:30', 'cls-1', 't-0', 's-0', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-8', 'Sabtu', '10:45 - 11:30', 'cls-2', 't-1', 's-1', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-9', 'Sabtu', '10:45 - 11:30', 'cls-3', 't-2', 's-2', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-10', 'Sabtu', '10:45 - 11:30', 'cls-4', 't-3', 's-3', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-11', 'Sabtu', '10:45 - 11:30', 'cls-5', 't-4', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-12', 'Sabtu', '10:45 - 11:30', 'cls-6', 't-5', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-13', 'Sabtu', '10:45 - 11:30', 'cls-7', 't-6', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-14', 'Sabtu', '12:30 - 13:00', 'cls-1', 't-7', 's-5', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-15', 'Sabtu', '12:30 - 13:00', 'cls-2', 't-0', 's-0', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-16', 'Sabtu', '12:30 - 13:00', 'cls-3', 't-4', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-17', 'Sabtu', '12:30 - 13:00', 'cls-4', 't-8', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-18', 'Sabtu', '12:30 - 13:00', 'cls-5', 't-2', 's-2', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-19', 'Sabtu', '12:30 - 13:00', 'cls-6', 't-5', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-20', 'Sabtu', '13:00 - 13:30', 'cls-1', 't-7', 's-5', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-21', 'Sabtu', '13:00 - 13:30', 'cls-2', 't-0', 's-0', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-22', 'Sabtu', '13:00 - 13:30', 'cls-3', 't-4', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-23', 'Sabtu', '13:00 - 13:30', 'cls-4', 't-8', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-24', 'Sabtu', '13:00 - 13:30', 'cls-5', 't-2', 's-2', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-25', 'Sabtu', '13:00 - 13:30', 'cls-6', 't-5', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-26', 'Ahad', '10:00 - 10:45', 'cls-1', 't-9', 's-6', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-27', 'Ahad', '10:00 - 10:45', 'cls-2', 't-8', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-28', 'Ahad', '10:00 - 10:45', 'cls-3', 't-10', 's-1', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-29', 'Ahad', '10:00 - 10:45', 'cls-4', 't-11', 's-2', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-30', 'Ahad', '10:00 - 10:45', 'cls-5', 't-4', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-31', 'Ahad', '10:00 - 10:45', 'cls-6', 't-9', 's-6', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-32', 'Ahad', '10:00 - 10:45', 'cls-7', 't-6', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-33', 'Ahad', '10:45 - 11:30', 'cls-1', 't-9', 's-6', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-34', 'Ahad', '10:45 - 11:30', 'cls-2', 't-8', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-35', 'Ahad', '10:45 - 11:30', 'cls-3', 't-10', 's-1', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-36', 'Ahad', '10:45 - 11:30', 'cls-4', 't-11', 's-2', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-37', 'Ahad', '10:45 - 11:30', 'cls-5', 't-4', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-38', 'Ahad', '10:45 - 11:30', 'cls-6', 't-9', 's-6', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-39', 'Ahad', '10:45 - 11:30', 'cls-7', 't-6', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-40', 'Ahad', '12:30 - 13:00', 'cls-1', 't-12', 's-7', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-41', 'Ahad', '12:30 - 13:00', 'cls-2', 't-13', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-42', 'Ahad', '12:30 - 13:00', 'cls-3', 't-9', 's-9', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-43', 'Ahad', '12:30 - 13:00', 'cls-4', 't-13', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-44', 'Ahad', '12:30 - 13:00', 'cls-5', 't-14', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-45', 'Ahad', '12:30 - 13:00', 'cls-6', 't-14', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-46', 'Ahad', '12:30 - 13:00', 'cls-7', 't-13', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-47', 'Ahad', '13:00 - 13:30', 'cls-1', 't-12', 's-7', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-48', 'Ahad', '13:00 - 13:30', 'cls-2', 't-13', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-49', 'Ahad', '13:00 - 13:30', 'cls-3', 't-9', 's-9', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-50', 'Ahad', '13:00 - 13:30', 'cls-4', 't-13', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-51', 'Ahad', '13:00 - 13:30', 'cls-5', 't-14', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-52', 'Ahad', '13:00 - 13:30', 'cls-6', 't-14', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-53', 'Ahad', '13:00 - 13:30', 'cls-7', 't-13', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-54', 'Senin', '10:00 - 10:45', 'cls-1', 't-10', 's-1', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-55', 'Senin', '10:00 - 10:45', 'cls-2', 't-8', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-56', 'Senin', '10:00 - 10:45', 'cls-3', 't-15', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-57', 'Senin', '10:00 - 10:45', 'cls-4', 't-16', 's-5', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-58', 'Senin', '10:00 - 10:45', 'cls-5', 't-17', 's-3', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-59', 'Senin', '10:00 - 10:45', 'cls-6', 't-5', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-60', 'Senin', '10:00 - 10:45', 'cls-7', 't-6', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-61', 'Senin', '10:45 - 11:30', 'cls-1', 't-10', 's-1', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-62', 'Senin', '10:45 - 11:30', 'cls-2', 't-8', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-63', 'Senin', '10:45 - 11:30', 'cls-3', 't-15', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-64', 'Senin', '10:45 - 11:30', 'cls-4', 't-16', 's-5', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-65', 'Senin', '10:45 - 11:30', 'cls-5', 't-17', 's-3', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-66', 'Senin', '10:45 - 11:30', 'cls-6', 't-5', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-67', 'Senin', '10:45 - 11:30', 'cls-7', 't-6', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-68', 'Senin', '12:30 - 13:00', 'cls-1', 't-5', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-69', 'Senin', '12:30 - 13:00', 'cls-2', 't-13', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-70', 'Senin', '12:30 - 13:00', 'cls-3', 't-18', 's-10', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-71', 'Senin', '12:30 - 13:00', 'cls-4', 't-8', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-72', 'Senin', '12:30 - 13:00', 'cls-5', 't-19', 's-11', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-73', 'Senin', '12:30 - 13:00', 'cls-6', 't-14', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-74', 'Senin', '12:30 - 13:00', 'cls-7', 't-13', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-75', 'Senin', '13:00 - 13:30', 'cls-1', 't-5', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-76', 'Senin', '13:00 - 13:30', 'cls-2', 't-13', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-77', 'Senin', '13:00 - 13:30', 'cls-3', 't-18', 's-10', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-78', 'Senin', '13:00 - 13:30', 'cls-4', 't-8', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-79', 'Senin', '13:00 - 13:30', 'cls-5', 't-19', 's-11', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-80', 'Senin', '13:00 - 13:30', 'cls-6', 't-14', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-81', 'Senin', '13:00 - 13:30', 'cls-7', 't-13', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-82', 'Selasa', '10:00 - 10:45', 'cls-1', 't-5', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-83', 'Selasa', '10:00 - 10:45', 'cls-2', 't-8', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-84', 'Selasa', '10:00 - 10:45', 'cls-5', 't-20', 's-10', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-85', 'Selasa', '10:00 - 10:45', 'cls-6', 't-4', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-86', 'Selasa', '10:00 - 10:45', 'cls-7', 't-5', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-87', 'Selasa', '10:45 - 11:30', 'cls-1', 't-5', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-88', 'Selasa', '10:45 - 11:30', 'cls-2', 't-8', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-89', 'Selasa', '10:45 - 11:30', 'cls-5', 't-20', 's-10', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-90', 'Selasa', '10:45 - 11:30', 'cls-6', 't-4', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-91', 'Selasa', '10:45 - 11:30', 'cls-7', 't-5', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-92', 'Selasa', '12:30 - 13:00', 'cls-1', 't-21', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-93', 'Selasa', '12:30 - 13:00', 'cls-2', 't-22', 's-6', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-94', 'Selasa', '12:30 - 13:00', 'cls-3', 't-19', 's-11', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-95', 'Selasa', '12:30 - 13:00', 'cls-4', 't-23', 's-11', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-96', 'Selasa', '12:30 - 13:00', 'cls-5', 't-12', 's-12', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-97', 'Selasa', '12:30 - 13:00', 'cls-7', 't-22', 's-6', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-98', 'Selasa', '13:00 - 13:30', 'cls-1', 't-21', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-99', 'Selasa', '13:00 - 13:30', 'cls-2', 't-22', 's-6', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-100', 'Selasa', '13:00 - 13:30', 'cls-3', 't-19', 's-11', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-101', 'Selasa', '13:00 - 13:30', 'cls-4', 't-23', 's-11', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-102', 'Selasa', '13:00 - 13:30', 'cls-5', 't-12', 's-12', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-103', 'Selasa', '13:00 - 13:30', 'cls-7', 't-22', 's-6', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-104', 'Rabu', '10:00 - 10:45', 'cls-1', 't-5', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-105', 'Rabu', '10:00 - 10:45', 'cls-2', 't-13', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-106', 'Rabu', '10:00 - 10:45', 'cls-3', 't-4', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-107', 'Rabu', '10:00 - 10:45', 'cls-4', 't-13', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-108', 'Rabu', '10:00 - 10:45', 'cls-5', 't-14', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-109', 'Rabu', '10:00 - 10:45', 'cls-6', 't-5', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-110', 'Rabu', '10:00 - 10:45', 'cls-7', 't-13', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-111', 'Rabu', '10:45 - 11:30', 'cls-1', 't-5', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-112', 'Rabu', '10:45 - 11:30', 'cls-2', 't-13', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-113', 'Rabu', '10:45 - 11:30', 'cls-3', 't-4', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-114', 'Rabu', '10:45 - 11:30', 'cls-4', 't-13', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-115', 'Rabu', '10:45 - 11:30', 'cls-5', 't-14', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-116', 'Rabu', '10:45 - 11:30', 'cls-6', 't-5', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-117', 'Rabu', '10:45 - 11:30', 'cls-7', 't-13', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-118', 'Rabu', '12:30 - 13:00', 'cls-1', 't-5', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-119', 'Rabu', '12:30 - 13:00', 'cls-2', 't-22', 's-6', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-120', 'Rabu', '12:30 - 13:00', 'cls-3', 't-15', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-121', 'Rabu', '12:30 - 13:00', 'cls-4', 't-8', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-122', 'Rabu', '12:30 - 13:00', 'cls-5', 't-18', 's-10', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-123', 'Rabu', '12:30 - 13:00', 'cls-6', 't-5', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-124', 'Rabu', '12:30 - 13:00', 'cls-7', 't-22', 's-6', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-125', 'Rabu', '13:00 - 13:30', 'cls-1', 't-5', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-126', 'Rabu', '13:00 - 13:30', 'cls-2', 't-22', 's-6', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-127', 'Rabu', '13:00 - 13:30', 'cls-3', 't-15', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-128', 'Rabu', '13:00 - 13:30', 'cls-4', 't-8', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-129', 'Rabu', '13:00 - 13:30', 'cls-5', 't-18', 's-10', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-130', 'Rabu', '13:00 - 13:30', 'cls-6', 't-5', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-131', 'Rabu', '13:00 - 13:30', 'cls-7', 't-22', 's-6', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-132', 'Kamis', '10:00 - 10:45', 'cls-1', 't-21', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-133', 'Kamis', '10:00 - 10:45', 'cls-2', 't-24', 's-5', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-134', 'Kamis', '10:00 - 10:45', 'cls-3', 't-25', 's-5', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-135', 'Kamis', '10:00 - 10:45', 'cls-4', 't-1', 's-1', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-136', 'Kamis', '10:00 - 10:45', 'cls-5', 't-26', 's-5', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-137', 'Kamis', '10:00 - 10:45', 'cls-6', 't-21', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-138', 'Kamis', '10:00 - 10:45', 'cls-7', 't-6', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-139', 'Kamis', '10:45 - 11:30', 'cls-1', 't-21', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-140', 'Kamis', '10:45 - 11:30', 'cls-2', 't-24', 's-5', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-141', 'Kamis', '10:45 - 11:30', 'cls-3', 't-25', 's-5', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-142', 'Kamis', '10:45 - 11:30', 'cls-4', 't-1', 's-1', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-143', 'Kamis', '10:45 - 11:30', 'cls-5', 't-26', 's-5', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-144', 'Kamis', '10:45 - 11:30', 'cls-6', 't-21', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-145', 'Kamis', '10:45 - 11:30', 'cls-7', 't-6', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-146', 'Kamis', '12:30 - 13:00', 'cls-1', 't-21', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-147', 'Kamis', '12:30 - 13:00', 'cls-2', 't-27', 's-7', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-148', 'Kamis', '12:30 - 13:00', 'cls-3', 't-28', 's-3', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-149', 'Kamis', '12:30 - 13:00', 'cls-4', 't-8', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-150', 'Kamis', '12:30 - 13:00', 'cls-5', 't-3', 's-13', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-151', 'Kamis', '13:00 - 13:30', 'cls-1', 't-21', 's-8', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-152', 'Kamis', '13:00 - 13:30', 'cls-2', 't-27', 's-7', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-153', 'Kamis', '13:00 - 13:30', 'cls-3', 't-28', 's-3', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-154', 'Kamis', '13:00 - 13:30', 'cls-4', 't-8', 's-4', 'ay-1', 'sem-1');
INSERT INTO teaching_schedules (id, day, time, class_id, teacher_id, subject_id, academic_year_id, semester_id) VALUES ('sch-new-155', 'Kamis', '13:00 - 13:30', 'cls-5', 't-3', 's-13', 'ay-1', 'sem-1');
