PRAGMA foreign_keys = OFF;
DELETE FROM santri;
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-1', '2026001', 'Ahmad Ajyad Syamil Sutrisno', 'cls-3');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-2', '2026002', 'Ahmad Fakhry Athallah', 'cls-3');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-3', '2026003', 'Athilasyah Rifqi Sulistyo', 'cls-3');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-4', '2026004', 'Baihaqi Hanif Abrorni', 'cls-3');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-5', '2026005', 'Fairuz Fahri Firmansyah', 'cls-3');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-6', '2026006', 'Hasbi Nafsi Jalalullah', 'cls-3');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-7', '2026007', 'Hisyam Zuhdi', 'cls-3');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-8', '2026008', 'Israr At Taufik', 'cls-3');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-9', '2026009', 'Keven Maghribi Darmaresta', 'cls-3');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-10', '2026010', 'Khoirul Akbar Nur Hidayatulloh', 'cls-3');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-11', '2026011', 'M Rajendra Ali Mudzakir', 'cls-3');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-12', '2026012', 'Muhammad Fatih Izzan An-Naqy', 'cls-3');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-13', '2026013', 'Muhammad Ilyas Anrisyab', 'cls-3');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-14', '2026014', 'Muhammad Yahya Izzuddin', 'cls-3');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-15', '2026015', 'Muhammad Yusuf Rifa''i', 'cls-3');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-16', '2026016', 'Ramdhan Ridhwanullah', 'cls-3');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-17', '2026017', 'Shofyan Abdillah Achmad', 'cls-3');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-18', '2026018', 'Tsaabit Qawiyyul Himmah', 'cls-3');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-19', '2026019', 'Yahya', 'cls-3');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-20', '2026020', 'Abigail Madhalee Ariya Fatihah', 'cls-4');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-21', '2026021', 'Alya Mukhbita', 'cls-4');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-22', '2026022', 'Ammara taqiyya khoirunnisa', 'cls-4');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-23', '2026023', 'Annisauzzahro as-salamah Parapat', 'cls-4');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-24', '2026024', 'Ayesha khayla Salsabila', 'cls-4');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-25', '2026025', 'Cataleya Azzahwa Fieary', 'cls-4');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-26', '2026026', 'Filzah Taqy Hilmiyah Hanief', 'cls-4');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-27', '2026027', 'Marwa Az Zahira Ibrahim Pribadi', 'cls-4');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-28', '2026028', 'Maryam Muthiah Tafdlila', 'cls-4');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-29', '2026029', 'Shabiha Nadira Azzahra', 'cls-4');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-30', '2026030', 'Syakila Nada Salsabila', 'cls-4');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-31', '2026031', 'Attahir Zarkasya Ramadhan', 'cls-1');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-32', '2026032', 'Bintang Bumi Langit Biru', 'cls-1');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-33', '2026033', 'Handade Yonca Satya Harjuna', 'cls-1');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-34', '2026034', 'Kenzie Iffat Itoniwa', 'cls-1');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-35', '2026035', 'Miqdaad Dzakiyy Hasan Faishal', 'cls-1');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-36', '2026036', 'Sae Sibghotallah', 'cls-1');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-37', '2026037', 'Imtihan Syarifatul ''Ula', 'cls-2');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-38', '2026038', 'Iskanda Aulia Neisya', 'cls-2');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-39', '2026039', 'Naura Auni Qonita', 'cls-2');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-40', '2026040', 'Adit Wahyu Pratama', 'cls-5');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-41', '2026041', 'Azka Rasya Darmawan', 'cls-5');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-42', '2026042', 'Badar Farisul Qital', 'cls-5');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-43', '2026043', 'Farzan Fiza Ananta', 'cls-5');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-44', '2026044', 'Hamidurohman Hudzaifi', 'cls-5');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-45', '2026045', 'Hilmi Dzabihulloh', 'cls-5');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-46', '2026046', 'Muhammad Faathir Rusyada Azhar', 'cls-5');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-47', '2026047', 'Nizar Haidar Rahman', 'cls-5');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-48', '2026048', 'Raushan Akhtar Majid', 'cls-5');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-49', '2026049', 'Tristan Firafisa Parsa', 'cls-5');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-50', '2026050', 'Yafiq Alvaro', 'cls-5');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-51', '2026051', 'Yuwhay Haura Anbiiya', 'cls-5');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-52', '2026052', 'Raisa Shakila Putri', 'cls-6');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-53', '2026053', 'Shofiyyah Afnan', 'cls-6');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-54', '2026054', 'Dzakira Tsania Fahmi', 'cls-6');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-55', '2026055', 'Rafanda Rayyan Adeeva', 'cls-6');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-56', '2026056', 'Hafidzah Mumtaazah Ni''matullah', 'cls-6');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-57', '2026057', 'Hurin Iin Luluil Maknun', 'cls-6');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-58', '2026058', 'Queena Kayyisa Nararya', 'cls-6');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-59', '2026059', 'Abdurrahman Az Zubair', 'cls-7');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-60', '2026060', 'Achmad Akmal Alhakim', 'cls-7');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-61', '2026061', 'Ahza Ibnu Hafiz', 'cls-7');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-62', '2026062', 'Albanna Sheeva', 'cls-7');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-63', '2026063', 'Arman Abdurrahman Nasution', 'cls-7');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-64', '2026064', 'Faiq Kamal Yazid Al-Bara', 'cls-7');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-65', '2026065', 'Jaisy Aliy Al Khalil', 'cls-7');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-66', '2026066', 'Mirza Alzam Azhari', 'cls-7');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-67', '2026067', 'Moh Khalifatullah Rosyad Al Amin', 'cls-7');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-68', '2026068', 'Muhammad Faruq Baharta', 'cls-7');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-69', '2026069', 'Muhammad Faqih Multazim', 'cls-7');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-70', '2026070', 'Muhammad Zidan Dhiyauddin', 'cls-7');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-71', '2026071', 'Rafasya Muhammad Firdaus An''Naba', 'cls-7');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-72', '2026072', 'Vajradhatu Keinan Noor', 'cls-7');
INSERT INTO santri (id, nis, name, class_id) VALUES ('santri-73', '2026073', 'Ziyad Alhaq', 'cls-7');
