DELETE FROM teaching_schedules;
DELETE FROM santri;
DELETE FROM semesters;
DELETE FROM academic_years;
DELETE FROM subjects;
DELETE FROM classes;
DELETE FROM users;
DELETE FROM teachers;
INSERT INTO academic_years (id, name) VALUES ('ay-1', '2023/2024');
INSERT INTO academic_years (id, name) VALUES ('ay-2', '2024/2025');
INSERT INTO semesters (id, name) VALUES ('sem-1', 'Ganjil');
INSERT INTO semesters (id, name) VALUES ('sem-2', 'Genap');
INSERT INTO classes (id, name, level) VALUES ('cls-1', '1 (Satu)', '1');
INSERT INTO classes (id, name, level) VALUES ('cls-2', '2 (Dua)', '2');
INSERT INTO classes (id, name, level) VALUES ('cls-3', '3 (Tiga)', '3');
INSERT INTO classes (id, name, level) VALUES ('cls-4', '4 (Empat)', '4');
INSERT INTO classes (id, name, level) VALUES ('cls-5', '5 (Lima)', '5');
INSERT INTO classes (id, name, level) VALUES ('cls-6', '6 (Enam)', '6');
INSERT INTO classes (id, name, level) VALUES ('cls-7', '7 (Tujuh)', '7');
INSERT INTO subjects (id, name) VALUES ('sub-1', 'Al Quran & Tajwid');
INSERT INTO subjects (id, name) VALUES ('sub-2', 'Aqidah & Tauhid');
INSERT INTO subjects (id, name) VALUES ('sub-3', 'Akhlaq / Adab');
INSERT INTO subjects (id, name) VALUES ('sub-4', 'Fiqih & Ibadah');
INSERT INTO subjects (id, name) VALUES ('sub-5', 'Sejarah Islam (Tarikh)');
INSERT INTO subjects (id, name) VALUES ('sub-6', 'Bahasa Arab');
INSERT INTO subjects (id, name) VALUES ('sub-7', 'Hafalan Hadits');
INSERT INTO subjects (id, name) VALUES ('sub-8', 'Hafalan Doa Sehari-hari');
INSERT INTO subjects (id, name) VALUES ('sub-9', 'Praktek Ibadah');
INSERT INTO subjects (id, name) VALUES ('sub-10', 'Tahsin');
INSERT INTO subjects (id, name) VALUES ('sub-11', 'Tahfidz');
INSERT INTO subjects (id, name) VALUES ('sub-12', 'Khot / Menulis Arab');
INSERT INTO subjects (id, name) VALUES ('sub-13', 'Bahasa Indonesia');
INSERT INTO subjects (id, name) VALUES ('sub-14', 'Matematika');
INSERT INTO subjects (id, name) VALUES ('sub-15', 'Ilmu Pengetahuan Alam (IPA)');
INSERT INTO subjects (id, name) VALUES ('sub-16', 'Pendidikan Jasmani & Kesehatan');
INSERT INTO users (id, name, email, role, teacher_id) VALUES ('user-admin-1', 'Aqli', 'aidilibnusalam3@gmail.com', 'Admin', NULL);
