UPDATE teachers SET name = 'Ustadz Abdul Malik' WHERE id = 't-0';
UPDATE teachers SET name = 'Ustadz Umar Alamuddin, Lc., Al-Hafizh' WHERE id = 't-1';
UPDATE teachers SET name = 'Ustadz Dzulfikar Tri Bagaskara, S.Ag., M.Pd.' WHERE id = 't-2';
UPDATE teachers SET name = 'Ustadz Nashiruddin Karim, Lc., Al-Hafizh' WHERE id = 't-3';
UPDATE teachers SET name = 'Ustadz Fredy Susilo Supriyanto' WHERE id = 't-4';
UPDATE teachers SET name = 'Ustadz Abdullah' WHERE id = 't-5';
UPDATE teachers SET name = 'Ustadzah Anim' WHERE id = 't-6';
UPDATE teachers SET name = 'Ustadz Agib' WHERE id = 't-7';
UPDATE teachers SET name = 'Ustadzah Iffah' WHERE id = 't-8';
UPDATE teachers SET name = 'Ustadz Yunan Hidayat, Al Hafizh' WHERE id = 't-9';
UPDATE teachers SET name = 'Ustadz Faqih' WHERE id = 't-10';
UPDATE teachers SET name = 'Ustadzah Indri Nurbidari, S.Si' WHERE id = 't-11';
UPDATE teachers SET name = 'Ustadz Aidil Aqli, S.Ag.' WHERE id = 't-12';
UPDATE teachers SET name = 'Ustadzah Saiba Musyaiya' WHERE id = 't-13';
UPDATE teachers SET name = 'Ustadz Muhammad Arya Mukti, Al Hafizh' WHERE id = 't-14';
UPDATE teachers SET name = 'Ustadz Kholif' WHERE id = 't-15';
UPDATE teachers SET name = 'Ustadzah Bela Dwi Lestari, S.Pd.' WHERE id = 't-16';
UPDATE teachers SET name = 'Ustadz Farhan' WHERE id = 't-17';
UPDATE teachers SET name = 'Ustadz Tubagus' WHERE id = 't-18';
UPDATE teachers SET name = 'Ustadz Muhammad Hafizh Hibatullah, S.Si.' WHERE id = 't-19';
UPDATE teachers SET name = 'Ustadzah Fani' WHERE id = 't-20';
UPDATE teachers SET name = 'Ustadz Azri Robani Indra Robbi, S.Ag.' WHERE id = 't-21';
UPDATE teachers SET name = 'Ustadzah Dila' WHERE id = 't-22';
UPDATE teachers SET name = 'Ustadzah Azizah' WHERE id = 't-23';
UPDATE teachers SET name = 'Ustadzah Hasri Haryani Direja, S.Ds.' WHERE id = 't-24';
UPDATE teachers SET name = 'Ustadz Muhammad Latief Amiruddin, S.T.' WHERE id = 't-25';
UPDATE teachers SET name = 'Ustadz Akmal' WHERE id = 't-26';
UPDATE teachers SET name = 'Ustadzah Lina Ayu Fitriyyah, S. Ag.' WHERE id = 't-27';
UPDATE teachers SET name = 'Ustadz Sahmura Maula Maghribi, S.Mat.' WHERE id = 't-28';
