UPDATE teachers SET name = 'Ust. Muhammad Abdul Malik Ibrahim, S.Kom' WHERE id = 't-0';
UPDATE teachers SET name = 'Ust. Umar Alamuddin, Lc., Al-Hafizh' WHERE id = 't-1';
UPDATE teachers SET name = 'Ust. Dzulfikar Tri Baskara, S.Ag, M.Pd' WHERE id = 't-2';
UPDATE teachers SET name = 'Ust. Nashiruddin Karim, Lc., Al-Hafizh' WHERE id = 't-3';
UPDATE teachers SET name = 'Ust. Fredy Susilo Supriyanto, S.Ag., Al Hafizh' WHERE id = 't-4';
UPDATE teachers SET name = 'Ust. Muhammad Ilyas Abdullah' WHERE id = 't-5';
UPDATE teachers SET name = 'Usth. Aulia Anim Amanillah' WHERE id = 't-6';
UPDATE teachers SET name = 'Usth. Iffah Luthfiyah' WHERE id = 't-8';
UPDATE teachers SET name = 'Ust. Yunan Hidayat, Al Hafizh' WHERE id = 't-9';
UPDATE teachers SET name = 'Ust. Faqih Hidayat,Lc' WHERE id = 't-10';
UPDATE teachers SET name = 'Usth. Indri Nur Bidari, S.Si' WHERE id = 't-11';
UPDATE teachers SET name = 'Ust. Aidil Aqli, S.Ag.' WHERE id = 't-12';
UPDATE teachers SET name = 'Ust. M. Arya Mukti al-Hafizh' WHERE id = 't-14';
UPDATE teachers SET name = 'Ust. Abdul Kholif al-Hafizh' WHERE id = 't-15';
UPDATE teachers SET name = 'Usth. Bela Dwi Lestari,S.pd., Gr' WHERE id = 't-16';
UPDATE teachers SET name = 'Ust. Farhan Akhandi' WHERE id = 't-17';
UPDATE teachers SET name = 'Ust. Tubagus Ahadiyat Rachmadi Luhur, S. Ag.' WHERE id = 't-18';
UPDATE teachers SET name = 'Ust. Muhammad Hafizh, S.Si' WHERE id = 't-19';
UPDATE teachers SET name = 'Usth. Rifanisa Nurulfitria, S.Hum., M.Si.' WHERE id = 't-20';
UPDATE teachers SET name = 'Ust. Azri Robani Indra Robbi, S.Ag.' WHERE id = 't-21';
UPDATE teachers SET name = 'Usth. Azizah Nur Aini, S.Pd., Gr' WHERE id = 't-23';
UPDATE teachers SET name = 'Usth. Hasri Haryani Direja, S.Ds' WHERE id = 't-24';
UPDATE teachers SET name = 'Ust. Muhammad Latief Amiruddin, S.T.' WHERE id = 't-25';
UPDATE teachers SET name = 'Ust. Akmal Firmana, ST' WHERE id = 't-26';
UPDATE teachers SET name = 'Usth. Lina Ayu Fitriyyah, S. Ag.' WHERE id = 't-27';
UPDATE teachers SET name = 'Ust. Rezkidar' WHERE id = 't-28';
